/* 
 * Demo Client for Passmeister Apple Wallet and Google Wallet API
 *
 * [www.passmeister.com](https://www.passmeister.com).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PassApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PassApiTests
    {
        private PassApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PassApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PassApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PassApi
            //Assert.IsInstanceOfType(typeof(PassApi), instance, "instance is a PassApi");
        }

        
        /// <summary>
        /// Test CreateOrUpdatePass
        /// </summary>
        [Test]
        public void CreateOrUpdatePassTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object passTypeId = null;
            //Object passId = null;
            //instance.CreateOrUpdatePass(passTypeId, passId);
            
        }
        
        /// <summary>
        /// Test DeletePass
        /// </summary>
        [Test]
        public void DeletePassTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object passTypeId = null;
            //Object passId = null;
            //instance.DeletePass(passTypeId, passId);
            
        }
        
        /// <summary>
        /// Test GetPass
        /// </summary>
        [Test]
        public void GetPassTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object passTypeId = null;
            //Object passId = null;
            //instance.GetPass(passTypeId, passId);
            
        }
        
        /// <summary>
        /// Test PassList
        /// </summary>
        [Test]
        public void PassListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object passTypeId = null;
            //Object page = null;
            //Object limit = null;
            //instance.PassList(passTypeId, page, limit);
            
        }
        
        /// <summary>
        /// Test PassSync
        /// </summary>
        [Test]
        public void PassSyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object passTypeId = null;
            //instance.PassSync(passTypeId);
            
        }
        
    }

}
